name: Compilar App de iOS

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Mostrar versiones
      run: |
        xcodebuild -version
        swift --version

    - name: Configurar versión de Xcode
      run: |
        xcodebuild -version

    - name: Compilar el proyecto de iOS
      run: |
        xcodebuild -project "PayPay.xcodeproj" \
                   -scheme "PayPay" \
                   -sdk iphoneos \
                   -configuration Release \
                   -derivedDataPath build \
                   CODE_SIGNING_ALLOWED=NO \
                   clean build

    - name: Ubicar archivos compilados
      run: |
        find build -name "*.app" -o -name "*.ipa"

    - name: Subir ejecutable compilado
      uses: actions/upload-artifact@v4
      with:
        name: App-Compilada
        path: build/Build/Products/Release-iphoneos/
        retention-days: 30
